=== DemidRoll1994/16JavaST2019/task04/src/by/name/tariffs111..xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/tariffs"
           xmlns:xsi="http://www.example.com/tariffs"
           elementFormDefault="qualified">

    <xs:element name="tariff" type="xsi:Tariff" abstract="true"/>
    <xs:element name="mobileInternetTariff" type="xsi:MobileInternetTariff"
                substitutionGroup="xsi:tariff"/>
    <xs:element name="mobileVoiceTariff" type="xsi:MobileVoiceTariff"
                substitutionGroup="xsi:tariff"/>

    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tariff"
                            type="xsi:Tariff"
                            minOccurs="0"
                            maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Tariff">
        <xs:all>
            <xs:element type="xs:double" name="payroll"/>
            <xs:element type="xs:double" name="smsPrices"/>
            <xs:element name="operator" default="A1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="A1"/>
                        <xs:enumeration value="MTC"/>
                        <xs:enumeration value="Life"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="parameters" type="xsi:VoiceTariffsParameters"/>
        </xs:all>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:ID" name="id" use="required"/>
    </xs:complexType>


    <xs:complexType name="VoiceTariffsParameters">
        <xs:sequence>
            <xs:element type="xs:integer" name="favoriteNumberCount"/>
            <xs:element type="xs:integer" name="billingInSec"/>
            <xs:element type="xs:double" name="prepayment"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InternetTariffsParameters">
        <xs:sequence>
            <xs:element type="xs:double" name="billingInMB"/>
            <xs:element type="xs:double" name="prepayment"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="CallPrices">
        <xs:sequence>
            <xs:element type="xs:double" name="inner"/>
            <xs:element type="xs:double" name="outer"/>
            <xs:element type="xs:double" name="linear"/>
        </xs:sequence>
    </xs:complexType>


    <!-- todo
    <xs:complexType name="InternetPrices">
        <xs:sequence>
            <xs:element type="xs:double" name="includedTraffic"/>
            <xs:element type="xs:double" name="outer"/>
            <xs:element type="xs:double" name="linear"/>
        </xs:sequence>
    </xs:complexType>
    -->

    <xs:complexType name="MobileVoiceTariff">
        <xs:complexContent>
            <xs:extension base="xsi:Tariff">
                <xs:sequence>
                    <xs:element name="callPrices" type="xsi:CallPrices"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MobileInternetTariff">
        <xs:complexContent>
            <xs:extension base="xsi:Tariff">
                <xs:sequence>
                    <xs:element name="internetPrices"
                                type="xsi:InternetPrices"/>
                    <xs:element name="TariffsParameters"
                                type="xsi:InternetTariffsParameters"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


</xs:schema>

=== DemidRoll1994/16JavaST2019/task04/src/by/name/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="tariffs111..xsd">
    <mobileVoiceTariff name="Comfort S" id="id1">
        <operator>A1</operator>
        <payroll>12.99</payroll>
        <callPrices>
            <inner>0</inner>
            <outer>0.075</outer>
            <linear>0.075</linear>
        </callPrices>
        <smsPrices>0.025</smsPrices>
        <parameters>
            <favoriteNumberCount>0</favoriteNumberCount>
            <billingInSec>60</billingInSec>
            <prepayment>5</prepayment>
        </parameters>
    </mobileVoiceTariff>

    <mobileVoiceTariff name="Comfort M" id="2">
        <operator>A1</operator>
        <payroll>17.99</payroll>
        <callPrices>
            <inner>0</inner>
            <outer>0.035</outer>
            <linear>0.035</linear>
        </callPrices>
        <smsPrices>0.025</smsPrices>
        <parameters>
            <favoriteNumberCount>0</favoriteNumberCount>
            <billingInSec>60</billingInSec>
            <prepayment>5</prepayment>
        </parameters>
    </mobileVoiceTariff>

    <mobileVoiceTariff name="Comfort L" id="id3">
        <operator>A1</operator>
        <payroll>25.99</payroll>
        <callPrices>
            <inner>0</inner>
            <outer>0.075</outer>
            <linear>0.075</linear>
        </callPrices>
        <smsPrices>0.025</smsPrices>
        <parameters>
            <favoriteNumberCount>0</favoriteNumberCount>
            <billingInSec>60</billingInSec>
            <prepayment>5</prepayment>
        </parameters>
    </mobileVoiceTariff>

    <mobileVoiceTariff name="Lemon" id="id4">
        <operator>A1</operator>
        <payroll>29.99</payroll>
        <callPrices>
            <inner>0</inner>
            <outer>0.075</outer>
            <linear>0.075</linear>
        </callPrices>
        <smsPrices>0.025</smsPrices>
        <parameters>
            <favoriteNumberCount>0</favoriteNumberCount>
            <billingInSec>60</billingInSec>
            <prepayment>5</prepayment>
        </parameters>
    </mobileVoiceTariff>


</tariffs>
